# Generated by Django 3.2.6 on 2021-08-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibehunt_api', '0002_auto_20210811_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='neighborhood',
            field=models.CharField(default='Midtown', max_length=255),
            preserve_default=False,
        ),
    ]
